src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookRepository")
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=75, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $synopsis;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $short_synopsis;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $size;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="books", cascade={"persist"})
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getShortSynopsis(): ?string
    {
        return $this->short_synopsis;
    }

    public function setShortSynopsis(?string $short_synopsis): self
    {
        $this->short_synopsis = $short_synopsis;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(?int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id')
            ->add('title',null,[
                'attr'=>[
                    'class'=>'form-control input-floating',
                    'placeholder'=>"Enter a title",
                ],
                'label'=> 'Title',
                'label_attr'=>[
                    'class'=>"label-floating"
                ],
            ])
            ->add('synopsis',null,[
                'attr'=>[
                    'class'=>'form-control input-floating',
                    'placeholder'=>"Enter a synopsis",
                ],
                'label'=> 'Synopsis',
                'label_attr'=>[
                    'class'=>"label-floating"
                ],
            ])
            ->add('short_synopsis',null,[
                'attr'=>[
                    'class'=>'form-control input-floating',
                    'placeholder'=>"Enter a lil synopsis",
                ],
                'label'=> 'Short synopsis',
                'label_attr'=>[
                    'class'=>"label-floating"
                ],
            ])
            ->add('size',null,[
                'attr'=>[
                    'class'=>'form-control input-floating',
                    'placeholder'=>"Enter number of pages",
                ],
                'label'=> 'Size',
                'label_attr'=>[
                    'class'=>"label-floating"
                ],
            ])
            ->add('year',null,[
                'attr'=>[
                    'class'=>'form-control input-floating',
                    'placeholder'=>"Enter book year",
                ],
                'label'=> 'Year',
                'label_attr'=>[
                    'class'=>"label-floating"
                ],
            ])
            ->add('category',null,[
                'attr'=>[
                    'class'=>'form-control',
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/book")
 */
class BookController extends AbstractController
{
    /**
     * @Route("/", name="book_index", methods={"GET"})
     */
    public function index(BookRepository $bookRepository): Response
    {
        return $this->render('book/index.html.twig', [
            'books' => $bookRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="book_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($book);
            $entityManager->flush();

            return $this->redirectToRoute('book_index');
        }

        return $this->render('book/new.html.twig', [
            'book' => $book,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="book_show", methods={"GET"})
     */
    public function show(Book $book): Response
    {
        return $this->render('book/show.html.twig', [
            'book' => $book,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="book_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Book $book): Response
    {
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('book_index');
        }

        return $this->render('book/edit.html.twig', [
            'book' => $book,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="book_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Book $book): Response
    {
        if ($this->isCsrfTokenValid('delete'.$book->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($book);
            $entityManager->flush();
        }

        return $this->redirectToRoute('book_index');
    }
}

templates/book/_delete_form.html.twig
<form method="post" action="{{ path('book_delete', {'id': book.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="btn btn-primary">Delete</button>
</form>

templates/book/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary" >{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Book{% endblock %}

{% block body %}
    <h1>Edit Book</h1>

    {{ include('book/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-primary"   href="{{ path('book_index') }}">back to list</a>

    {{ include('book/_delete_form.html.twig') }}
{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book index{% endblock %}

{% block body %}
    <div class="">

    <h1 class="text-center">Book list</h1><br/>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Synopsis</th>
                <th>Short synopsis</th>
                <th>Cateogry</th>
                <th>Size</th>
                <th>Year</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.id }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.synopsis|slice(0,75)~"..." }}</td>
                <td>{{ book.shortSynopsis }}</td>
                <td>{{ book.category }}</td>
                <td>{{ book.size }}</td>
                <td>{{ book.year }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('book_show', {'id': book.id}) }}">show</a>
                    <a class="btn btn-primary" href="{{ path('book_edit', {'id': book.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('book_new') }}">Create new</a>
    </div>
{% endblock %}

templates/book/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Book{% endblock %}

{% block body %}
    <h1>Create new Book</h1>

    {{ include('book/_form.html.twig') }}

    <a class="btn btn-primary" href="{{ path('book_index') }}">back to list</a>
{% endblock %}

templates/book/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book{% endblock %}

{% block body %}
    <h1>Book</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ book.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ book.title }}</td>
            </tr>
            <tr>
                <th>Synopsis</th>
                <td>{{ book.synopsis }}</td>
            </tr>
            <tr>
                <th>Short_synopsis</th>
                <td>{{ book.shortSynopsis }}</td>
            </tr>
            <tr>
                <th>Size</th>
                <td>{{ book.size }}</td>
            </tr>
            <tr>
                <th>Year</th>
                <td>{{ book.year }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('book_index') }}">back to list</a>

    <a class="btn btn-primary" href="{{ path('book_edit', {'id': book.id}) }}">edit</a>

    {{ include('book/_delete_form.html.twig') }}
{% endblock %}